name: Veracode Upload and Scan
on:
  # Run once monthly
  pull_request:
    types: [opened, reopened]

  # Allow manual runs to be triggered  
  workflow_dispatch:

jobs:
  static_analysis:
    uses: seismic/github-actions/.github/workflows/veracode.yml@master
    secrets: inherit
    with:
      ruby: true
